INSERT INTO REVIEW
VALUES(SEQ_REVIEW.NEXTVAL,
       '정말 넘모 조와용',
       '어쩜 이리 섬세하신지..홍홍',
       SYSDATE,
       '만족하셨다니 기분이 좋네요',
       SYSDATE,
       'Y',
       NULL,
       1);
       
SELECT R.START_DATE,
       R.END_DATE,
       ADDRESS,
       CA_STATUS,
       P_TITLE,
       CARE_LIST,
       P_NO,
       A.FILE_PATH AS FILE_PATH,
       ORIGIN_NAME,
       (SELECT COUNT(*) FROM REVIEW WHERE REF_RESNO = R.RES_NO) AS REVIEW_COUNT
FROM RESERVATION R
 JOIN MEMBER M ON R.USER_NO = M.USER_NO
 JOIN PETSITTER P ON R.REF_PNO = P.P_NO
 JOIN P_ATTACHMENT A ON P.P_NO = A.REF_PNO
WHERE R.USER_NO = 2;
       
       
       ROLLBACK;
       
SELECT * FROM RESERVATION
ORDER BY REGISTER_DATE DESC;

SELECT R.START_DATE,
       R.END_DATE,
       M.ADDRESS,
       M.CA_STATUS,
       P.P_TITLE,
       P.CARE_LIST,
       P.P_NO,
       A.FILE_PATH AS FILE_PATH,
       A.ORIGIN_NAME,
       (SELECT COUNT(*) FROM REVIEW WHERE REF_RESNO = R.RES_NO) AS REVIEW_COUNT
FROM RESERVATION R
JOIN MEMBER M ON R.USER_NO = M.USER_NO
JOIN PETSITTER P ON R.REF_PNO = P.P_NO
JOIN P_ATTACHMENT A ON P.P_NO = A.REF_PNO
LEFT JOIN REVIEW ON R.RES_NO = REVIEW.REF_RESNO
WHERE R.USER_NO = 2
ORDER BY R.START_DATE DESC;


		SELECT 
		CASE WHEN REV.REV_NO IS NOT NULL THEN 1 ELSE 0 END AS REVIEW_STATUS
		FROM MEMBER M
		JOIN RESERVATION R ON M.USER_NO = R.USER_NO
		LEFT JOIN REVIEW REV ON R.RES_NO = REV.REF_RESNO
		WHERE M.USER_NO = 2
		  AND R.REF_PNO = 4;	